name: Package Application with Pyinstaller

on:
  push:
    branches:
      - main  # Modify this based on the branch you want to trigger the action on

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r ./src/requirements.txt
        pip install pyinstaller

    - name: Build executable (no console)
      run: pyinstaller ./src/main.py --onefile -n "Discord Rich Presence" -i favicon.ico --noconsole

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-executable-no-console
        path: './dist/Discord Rich Presence.exe'

    - name: Build executable
      run: pyinstaller ./src/main.py --onefile -n "Discord Rich Presence" -i favicon.ico

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-executable-console
        path: './dist/Discord Rich Presence.exe'
