name: Package Application with Pyinstaller

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable (no console)
      run: pyinstaller main.py --onefile -n "Discord Rich Presence" -i favicon.ico --collect-data ytmusicapi --noconsole --add-data "favicon.ico;."

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Discord Rich Presence (no console)
        path: './dist/Discord Rich Presence.exe'

    - name: Build executable
      run: pyinstaller main.py --onefile -n "Discord Rich Presence" -i favicon.ico --collect-data ytmusicapi --add-data "favicon.ico;."

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Discord Rich Presence (console)
        path: './dist/Discord Rich Presence.exe'
